"""Dependency inversion contracts for production adapters."""
from __future__ import annotations
from typing import Protocol, runtime_checkable
from .models import Measurement, TraceRecord, RecoveryRecord, StationId
from .ateq import AteqRequest, AteqResponse

@runtime_checkable
class AteqPort(Protocol):
    station: str
    def select_program(self, program: str) -> None: ...
    def start_test(self) -> None: ...
    def run(self, request: AteqRequest) -> AteqResponse: ...

@runtime_checkable
class RepositoryPort(Protocol):
    def insert_stage1(self, record: TraceRecord) -> TraceRecord: ...
    def update_stage2(self, cycle_id: str, measurement: Measurement) -> TraceRecord: ...
    def row_id(self, cycle_id: str) -> int | None: ...
    def get(self, cycle_id: str) -> TraceRecord | None: ...
    def mark_marked(self, cycle_id: str) -> None: ...
    def query(self, text: str = "") -> list[TraceRecord]: ...

@runtime_checkable
class MarkerPort(Protocol):
    def mark(self, record: TraceRecord) -> "MarkReceipt": ...

@runtime_checkable
class PlcPort(Protocol):
    def read_bit(self, byte: int, bit: int) -> bool: ...
    def write_bit(self, byte: int, bit: int, value: bool) -> None: ...
    def health(self) -> bool: ...
    def outputs_energized(self) -> bool: ...

@runtime_checkable
class SafeStopPort(Protocol):
    def safe_stop(self, reason: str) -> None: ...


class JournalPort(Protocol):
    def write_record(self, record: RecoveryRecord) -> None: ...
    def recover_record(self) -> RecoveryRecord | None: ...


class MarkReceipt(Protocol):
    accepted: bool
    job_id: str
    receipt: str
